import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid grid-cols-1 grid-rows-5 lg:grid-rows-1 lg:grid-cols-5 items-center justify-items-center min-h-screen">
          <div className="flex flex-col col-span-1 row-span-2 lg:col-span-3 lg:row-span-1 items-center justify-center bg-slate-400 h-full w-full">
            <h1 className="text-6xl text-slate-300">Admint</h1>
            <p className="text-slate-800">User management portal</p>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
